HouseRentMVC/Controllers/PredictionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNetCore.Mvc;
using Microsoft.ML;
using System.Web.Mvc.Html;



namespace Prediction.Controllers
{
    public class PredictionController : Controller
    {
        [HttpGet]
        public ActionResult price()
        {
            if (Session["Login"] == null)
            {

                return RedirectToAction("Index", "Login");


            }
            // Load the model  
            MLContext mlContext = new MLContext();

            // Create predection engine related to the loaded train model  
            ITransformer mlModel = mlContext.Model.Load(@"C:\Users\320090153\source\repos\ASP.NET-MVC-HouseRent-Management-master\HouseRentMVCML.Model\MLModel.zip", out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<HouseRentMVCML.Model.ModelInput, HouseRentMVCML.Model.ModelOutput>(mlModel);


            return View();
        }
        [HttpPost]
        public ActionResult price(HouseRentMVCML.Model.ModelInput input)
        {
            Session["message"] = "New Area Added";

            // Load the model  
            MLContext mlContext = new MLContext();
            // Create predection engine related to the loaded train model  
            ITransformer mlModel = mlContext.Model.Load(@"C:\Users\320090153\source\repos\ASP.NET-MVC-HouseRent-Management-master\HouseRentMVCML.Model\MLModel.zip", out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<HouseRentMVCML.Model.ModelInput, HouseRentMVCML.Model.ModelOutput>(mlModel);

            // Try model on sample data to predict fair price  
            HouseRentMVCML.Model.ModelOutput result = predEngine.Predict(input);

            ViewBag.Price = result.Score;
            Console.WriteLine(result.Score);
            return View(input);
        }

    }
}

HouseRentMVC/Views/Prediction/Price.cshtml
@model HouseRentMVCML.Model.ModelInput

@{
    ViewData["Title"] = "Price Prediction Using ML.NET";
}


<center>

    <h2>Predict</h2>

    @using (Html.BeginForm("Price", "Prediction", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset style="width: 40%">


            <div class="editor-label">
                @Html.LabelFor(model => model.Locality)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Locality)
                <div class="error">
                    @Html.ValidationMessageFor(model => model.Locality)
                </div>

            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Area)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.Area)
                <div class="error">
                    @Html.ValidationMessageFor(model => model.Area)
                </div>

            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Bedrooms)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Bedrooms)
                <div class="error">
                    @Html.ValidationMessageFor(model => model.Bedrooms)
                </div>

            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Furnishing)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Furnishing)
            </div>


            <p>
                <input type="submit" value="Predict" />
            </p>
        </fieldset>
    }

    <div class="col-md-offset-2 col-md-4">
        @if (ViewBag.Price != null)
        {
            <h3>Result</h3>
            <h3>Approximate Rent Price:@ViewBag.Price</h3>
        }
    </div>
    <div>
        @Html.ActionLink("Back to Home", "Index", "Home")
    </div>
</center>